const ActionTypes = {
    SET_BOARD_DATA: 'SET_BOARD_DATA',
    SET_WINNER: 'SET_WINNER',
    SET_WINTYPE: 'SET_WINTYPE',
    SET_WININDEX: 'SET_WININDEX',
    SET_MOVE_HISTORY: 'SET_MOVE_HISTORY',
    SET_CURRENT_MOVE: 'SET_CURRENT_MOVE',
    SET_ISX: 'SET_ISX',
    SET_RESET_BOARD: 'SET_RESET_BOARD',
};

export default ActionTypes;