const ActionTypes = {
    SWITCH_NEXT_TURN_VALUE: 'SWITCH_NEXT_TURN_VALUE',
    SET_WINNER: 'SET_WINNER',
    RESET_WINNER: 'RESET_WINNER',
    UPDATE_CURRENT_MOVE: 'UPDATE_CURRENT_MOVE',
    RESET_GAME: 'RESET_GAME',
};

export default ActionTypes;